# Use custom format
format = """
[┌───────────────────❯](bold green)
[│](bold green)$username$hostname$directory$git_branch$git_status$git_commit$hg_branch$rust
[└─](bold green)$character"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[❯](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true
format = "[$user]($style)@"
style_user = "bold dimmed cyan"
style_root = "bold bright red"

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
style = "bold dimmed red"

[git_branch]
disabled = false

[hg_branch]
disabled = false

[shell]
disabled = false
