#!/bin/bash

RFCDIR=$HOME/.local/share/rfcs
MANIFEST=$RFCDIR/manifest.txt

RFCS=""
RFC_TXTS=""
NUM_RFCS=0
QUIET=0
LIST=0

while :
do
    case "$1" in
        -c | --clean)
            read -p "Are you sure you want to delete the rfc cache (y/n)? " answer
            EXIT_CODE=0
            case ${answer:0:1} in
                y|Y)
                    rm -rf ~/.local/share/rfcs
                    ;;
                n|N)
                    ;;
                *)
                    echo "Did not understand $answer."
                    EXIT_CODE=1
                    ;;
            esac
            exit $EXIT_CODE
            ;;
        -q | --quiet)
            QUIET=1
            shift
            ;;
        -l | --list)
            LIST=1
            shift
            ;;
        -h | --help)
            echo "$0 <rfc num>"
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            echo "$0 <rfc num>"
            exit 1
            ;;
        *)
            RFCS=$@
            break
            ;;
    esac
done

if [ $LIST -ne 0 ]
then
    if ! [ -f $RFCDIR/manifest.txt ]
    then
        for rfcfile in $(ls $RFCDIR)
        do
            rfc=$(echo $rfcfile | sed 's/rfc\([[:digit:]]\+\).txt/\1/g')
            curl https://tools.ietf.org/html/rfc$rfc -so - |\
                echo "$(grep -iPo '(?<=title>)(.*)(?=</title>)')" >> \
                $RFCDIR/manifest.txt
            if [ $? -ne 0 ]
            then
                echo "Failed to update manifest"
                exit 1
            fi
        done
    fi
    cat $RFCDIR/manifest.txt
    exit 0
fi

re='^[0-9]+$'
for rfc in ${RFCS[@]}
do
    if ! [[ $rfc =~ $re ]]
    then
        echo "$rfc is not a number"
        exit 1
    else
        if ! [ -d $RFCDIR ]
        then
            mkdir -p $RFCDIR
        fi
        if ! [ -f $RFCDIR/rfc$rfc.txt ]
        then
            echo "Downloading RFC: $rfc"
            curl https://tools.ietf.org/rfc/rfc$rfc.txt -o $RFCDIR/rfc$rfc.txt
            if [ $? -ne 0 ]
            then
                echo "Could not download rfc$1!"
                exit 1
            fi
            if ! [ -f $MANIFEST ] || ! grep "^RFC $rfc" -i $MANIFEST
            then
                curl https://tools.ietf.org/html/rfc$rfc -so - |\
                    echo "$(grep -iPo '(?<=title>)(.*)(?=</title>)')" >> \
                    $RFCDIR/manifest.txt
            fi
            sed -i 's/[\x0c\x0d]//g' $RFCDIR/rfc$rfc.txt
        fi
        RFC_TXTS="$RFC_TXTS $RFCDIR/rfc$rfc.txt"
    fi
    ((NUM_RFCS=NUM_RFCS+1))
done

if [ $QUIET -eq 0 ]
then
    if ! [ -f $RFCDIR/rfc$1.txt ]
    then
        echo "Could not download rfc$1!"
        exit 1
    else
        if [ $NUM_RFCS -eq 0 ]
        then
            echo "Must specify at least one rfc"
            exit 1
        elif [ $NUM_RFCS -eq 1 ]
        then
            exec $EDITOR -c "setfiletype rfc" -R $RFC_TXTS
        else
            exec $EDITOR -o 1 -c "setfiletype rfc" -R $RFC_TXTS
        fi
    fi
fi
